<<<<<<< HEAD
import './globals.css';
import { Inter } from 'next/font/google';
import DashboardLayout from '@/components/layout/DashboardLayout';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'GoClint - منصة اكتشاف المواهب الرياضية',
  description: 'منصة متكاملة تربط بين اللاعبين والأندية والمدربين',
=======
import { Inter } from "next/font/google";
import "./globals.css";
import { FirebaseAuthProvider } from "@/lib/firebase/auth-provider";


const inter = Inter({ 
  subsets: ["latin"],
  variable: '--font-inter'
});

export const metadata = {
  title: "HagzZ Go",
  description: "Generated by create next app",
>>>>>>> bca22f5650d9d75baeb93f1e7ba3fc2055bf8bd6
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ar" dir="rtl">
<<<<<<< HEAD
      <body className={inter.className}>
        <DashboardLayout>{children}</DashboardLayout>
=======
      <body className={`${inter.variable} font-sans bg-background text-foreground`}>
        <FirebaseAuthProvider>
          {children}
        </FirebaseAuthProvider>
>>>>>>> bca22f5650d9d75baeb93f1e7ba3fc2055bf8bd6
      </body>
    </html>
  );
}